language: node_js
node_js:
    - "lts/*"
branches:
    only:
        - master
cache:
    directories:
        - node_modules
    yarn: true
install:
    - yarn
script:
    - yarn build
deploy:
    repo: chhpt/chhpt.github.io
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: ./docs/.vuepress/dist/
    target-branch: gh-pages
    verbose: true
    on:
        branch: master
notifications:
  email:
    - cwuyiqing@foxmail.com