language: node_js
node_js:
    - "lts/*"
branches:
    only:
        - master
cache:
    directories:
        - node_modules
    yarn: true
install:
    - yarn
script:
    - yarn build
deploy:
    repo: chhpt/chhpt.github.io
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./docs/.vuepress/dist/
    verbose: true
    on:
        branch: master
notifications:
  email:
    - cwuyiqing@foxmail.com