# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:10.15.2
        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                        # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: Install dependency
                  command: yarn install
            - run:
                  name: Build docs
                  command: yarn run build
            - run:
                  name: Copy build files
                  command: cp -r pages/.vuepress/dist/* docs/

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - add_ssh_keys:
                  fingerprints:
                      - 'b0:50:e7:61:6e:1a:ca:7e:06:0e:ac:bc:3a:b1:bb:91'

            - deploy:
                  name: Trigger docs deployment, commit and push
                  command: |
                      git config user.email "cwuyiqing@gmail.com"
                      git config user.name "chhpt"
                      git add -A
                      git commit -m "circle ci build auto commit [ci skip]"
                      git push git@github.com:chhpt/the-web-full-stack-way.git master
